### ISSUE TITLE
Retirar a estratégia do Main System 

### ISSUE THREAD

**Issue by ayssag** [unball/MALP#5]
### Descrição

Dentro do Main System, retirar todos os blocos de código referente à estratégia.

**Comment by emmenezes** [comment]
Precisa:
Estudar visionMessage para enviar para o pickle e mudar arquivo de onde as mensagens são enviadas

**Comment by emmenezes** [comment]
Precisa:
Alterar local de envio dos dados do pickle e estudar VisionMessages
